# Generated by Django 5.2.6 on 2025-12-26 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('semences', 'Semences'), ('engrais', 'Engrais et amendements'), ('pesticides', 'Pesticides et herbicides'), ('equipement', 'Équipements et outils'), ('carburant', 'Carburant et énergie'), ('transport', 'Transport'), ('main_oeuvre', "Main d'œuvre supplémentaire"), ('irrigation', 'Irrigation'), ('stockage', 'Stockage et conservation'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie de dépense'),
        ),
        migrations.CreateModel(
            name='RapportIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du rapport')),
                ('donnees_graphiques', models.JSONField(default=dict, help_text='Données structurées (JSON) pour générer des graphiques sur le frontend', verbose_name='Données pour les graphiques')),
                ('analyse_complete', models.TextField(help_text="Texte détaillé de l'analyse générée par l'IA", verbose_name='Analyse complète')),
                ('propositions_amelioration', models.TextField(help_text="Liste des suggestions pour améliorer l'exploitation", verbose_name="Propositions d'amélioration")),
                ('points_progression', models.TextField(help_text="Analyse de l'évolution par rapport aux rapports précédents", verbose_name='Points de progression')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='rapports_pdf/', verbose_name='Fichier PDF')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_ia', to=settings.AUTH_USER_MODEL, verbose_name='Agriculteur')),
            ],
            options={
                'verbose_name': 'Rapport IA',
                'verbose_name_plural': 'Rapports IA',
                'ordering': ['-date_creation'],
            },
        ),
    ]
