# Generated by Django 5.2.6 on 2025-12-26 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0002_alter_depense_categorie_rapportia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='culture',
            field=models.ForeignKey(blank=True, help_text='Culture à laquelle cette dépense est liée (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='agri_app.culture', verbose_name='Culture associée'),
        ),
    ]
