# Generated by Django 5.2.6 on 2025-12-26 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0003_alter_depense_culture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, verbose_name='Titre de la conversation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'ordering': ['-date_mise_a_jour'],
            },
        ),
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_utilisateur', models.BooleanField(default=True, help_text="Vrai si le message vient de l'utilisateur, Faux si c'est l'IA", verbose_name="Est l'utilisateur ?")),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('contexte_donnees', models.JSONField(blank=True, help_text='Snapshot des données utilisées pour générer la réponse (si IA)', null=True, verbose_name='Données contextuelles')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agri_app.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message Chat',
                'verbose_name_plural': 'Messages Chat',
                'ordering': ['date_envoi'],
            },
        ),
    ]
