# Generated by Django 5.2.6 on 2026-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0005_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='plan_abonnement',
            field=models.CharField(choices=[('gratuit', 'Gratuit'), ('pro', 'Professionnel'), ('expert', 'Expert / Coopérative')], default='gratuit', max_length=20, verbose_name="Plan d'abonnement"),
        ),
    ]
