# Generated by Django 5.2.6 on 2026-01-14 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0007_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix')),
                ('unite', models.CharField(max_length=50, verbose_name='Unité (ex: kg, sac, tonne)')),
                ('quantite_disponible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité disponible')),
                ('categorie', models.CharField(choices=[('cereales', 'Céréales'), ('tubercules', 'Tubercules'), ('fruits', 'Fruits'), ('legumes', 'Légumes'), ('elevage', 'Élevage'), ('intrants', 'Semences & Intrants'), ('materiel', 'Matériel Agricole'), ('autre', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('localisation', models.CharField(max_length=255, verbose_name='Localisation du produit')),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/', verbose_name='Image du produit')),
                ('telephone_contact', models.CharField(max_length=20, verbose_name='Téléphone de contact')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('lien_externe', models.URLField(blank=True, null=True, verbose_name='Lien externe (ex: site web, WhatsApp)')),
                ('est_publie', models.BooleanField(default=False, verbose_name='Est publié')),
                ('paiement_effectue', models.BooleanField(default=False, verbose_name='Paiement frais de mise en rayon effectué')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Annonce Produit',
                'verbose_name_plural': 'Annonces Produits',
                'ordering': ['-date_creation'],
            },
        ),
    ]
