# Generated by Django 5.2.6 on 2026-04-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0008_produitannonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil'),
        ),
    ]
